customhost = "employee.c1rcjuzk2mzy.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leeyingshan-employee"
customregion = "us-east-1"
